import Foundation

/// Protocol defining the core functionality for the Lightpack library.
public protocol LightpackProtocol {
    /// A dictionary of all models, keyed by their model IDs.
    /// Each LPModel contains information about a specific model, including its status, size, and other metadata.
    var models: [String: LPModel] { get }
    
    /// A dictionary of all model families, keyed by their family IDs.
    /// Each `LPModelFamily` contains information about a group of related models.
    var families: [String: LPModelFamily] { get }

    /// The currently loaded model, if any.
    /// This will be `nil` if no model is currently loaded.
    var loadedModel: LPModel? { get }

    /// The total size of all downloaded models in bytes.
    var totalModelSize: Float { get }
    
    /// Clears the current chat context.
    ///
    /// This function removes all previous chat history and resets the chat state.
    /// It's useful for starting a new conversation or freeing up memory.
    ///
    /// - Throws: An error if the clearing process encounters any issues.
    func clearChat() async throws
    
    /// Cancels the download of a specific model.
    ///
    /// - Parameters:
    ///   - alias: The alias of the model to cancel download for (e.g., "qwen2").
    ///   - modelId: The unique identifier of the model to cancel download for (e.g., "23a77013-fe73-4f26-9ab2-33d315a71924").
    /// - Throws: An error if the cancellation process fails.
    func cancelDownloadModel(alias: String?, modelId: String?) async throws

    /// Initiates a chat interaction with a specified model.
    ///
    /// - Parameters:
    ///   - alias: The alias of the model to use for chat (e.g., "qwen2").
    ///   - modelId: The unique identifier of the model to use for chat (e.g., "23a77013-fe73-4f26-9ab2-33d315a71924").
    ///   - messages: An array of chat messages to provide context for the interaction.
    ///   - onToken: A closure that's called for each token generated by the model.
    /// - Throws: An error if the chat process encounters issues.
    func chatModel(alias: String?, modelId: String?, messages: [LPChatMessage], onToken: @escaping (String) -> Void) async throws

    /// Initiates the download of a specific model.
    ///
    /// - Parameters:
    ///   - alias: The alias of the model to use for chat (e.g., "qwen2").
    ///   - modelId: The unique identifier of the model to use for chat (e.g., "23a77013-fe73-4f26-9ab2-33d315a71924").
    /// - Throws: An error if the download process fails to start or complete.
    func downloadModel(alias: String?, modelId: String?) async throws
    
    /// Loads a specific model into memory.
    ///
    /// - Parameters:
    ///   - alias: The alias of the model to load (e.g., "qwen2").
    ///   - modelId: The unique identifier of the model to load (e.g., "23a77013-fe73-4f26-9ab2-33d315a71924").
    /// - Throws: An error if the model fails to load.
    func loadModel(alias: String?, modelId: String?) async throws

    /// Pauses the download of a specific model.
    ///
    /// - Parameters:
    ///   - alias: The alias of the model to pause download for (e.g., "qwen2").
    ///   - modelId: The unique identifier of the model to pause download for (e.g., "23a77013-fe73-4f26-9ab2-33d315a71924").
    /// - Throws: An error if the pause operation fails.
    func pauseDownloadModel(alias: String?, modelId: String?) async throws

    /// Removes one or more models from the local storage.
    ///
    /// - Parameters:
    ///   - aliases: An array of model aliases to remove (e.g., ["qwen2"]).
    ///   - modelIds: An array of model identifiers to remove (e.g., ["23a77013-fe73-4f26-9ab2-33d315a71924"]).
    ///   - removeAll: A boolean indicating whether to remove all locally stored models.
    /// - Throws: An error if the removal process fails.
    func removeModels(aliases: [String]?, modelIds: [String]?, removeAll: Bool) async throws

    /// Resumes the download of a previously paused model.
    ///
    /// - Parameters:
    ///   - alias: The alias of the model to resume download for (e.g., "qwen2").
    ///   - modelId: The unique identifier of the model to resume download for (e.g., "23a77013-fe73-4f26-9ab2-33d315a71924").
    /// - Throws: An error if the resume operation fails.
    func resumeDownloadModel(alias: String?, modelId: String?) async throws

    /// Retrieves a list of models based on specified criteria.
    ///
    /// - **Parameters**:
    ///   - aliases: An array of model aliases to filter by (e.g., ["qwen2"]) (optional).
    ///   - bitMax: The maximum number of bits for the model (e.g., 32) (optional).
    ///   - bitMin: The minimum number of bits for the model (e.g., 8) (optional).
    ///   - familyIds: An array of family identifiers to filter by (e.g., ["a9a97695-2573-4d12-99e0-371aae7ac009"] for Qwen2) (optional).
    ///   - modelIds: An array of specific model identifiers to retrieve (e.g., ["23a77013-fe73-4f26-9ab2-33d315a71924"] for Qwen2 1.5B q8_0) (optional).
    ///   - page: The page number for paginated results (e.g., 1) (optional).
    ///   - pageSize: The number of items per page (e.g., 10) (optional).
    ///   - parameterIds: An array of parameter identifiers to filter by (e.g., ["1.5B"]) (optional).
    ///   - quantizationIds: An array of quantization identifiers to filter by (e.g., ["q8_0"]) (optional).
    ///   - sizeMax: The maximum size of the model in GB (e.g., 2.0) (optional).
    ///   - sizeMin: The minimum size of the model in GB (e.g., 1.0) (optional).
    ///   - sort: A string indicating the sort order of the results (e.g., "size:desc") (optional).
    ///   - completion: A closure called with the result of the operation, containing the models response and an array of updated model IDs.
    func getModels(
        aliases: [String]?,
        bitMax: Int?,
        bitMin: Int?,
        familyIds: [String]?,
        modelIds: [String]?,
        page: Int?,
        pageSize: Int?,
        parameterIds: [String]?,
        quantizationIds: [String]?,
        sizeMax: Float?,
        sizeMin: Float?,
        sort: String?,
        completion: @escaping (Result<(LPModelsResponse, [String]), LPError>) -> Void
    )

    /// Retrieves a list of model families based on specified criteria.
    ///
    /// - **Parameters**:
    ///   - aliases: An array of family aliases to filter by (e.g., ["qwen2"]) (optional).
    ///   - authors: An array of authors to filter by (optional).
    ///   - familyIds: An array of family identifiers to retrieve (e.g., ["a9a97695-2573-4d12-99e0-371aae7ac009"] for Qwen2) (optional).
    ///   - modelParameterIds: An array of model parameter identifiers to filter by (e.g., ["1.5B"]) (optional).
    ///   - page: The page number for paginated results (e.g., 1) (optional).
    ///   - pageSize: The number of items per page (e.g., 10) (optional).
    ///   - sort: A string indicating the sort order of the results (e.g., "title:asc") (optional).
    ///   - titles: An array of titles to filter by (optional).
    ///   - updatedAfter: A date string to filter families updated after this date (optional).
    ///   - updatedBefore: A date string to filter families updated before this date (optional).
    ///   - completion: A closure called with the result of the operation, containing the model families response and an array of updated family IDs.
    func getModelFamilies(
        aliases: [String]?,
        authors: [String]?,
        familyIds: [String]?,
        modelParameterIds: [String]?,
        page: Int?,
        pageSize: Int?,
        sort: String?,
        titles: [String]?,
        updatedAfter: String?,
        updatedBefore: String?,
        completion: @escaping (Result<(LPModelFamiliesResponse, [String]), LPError>) -> Void
    )
}

@available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
public protocol URLSessionProtocol: Sendable {
    func dataTask(with request: URLRequest, completionHandler: @escaping @Sendable (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTask
}

@available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
extension URLSession: URLSessionProtocol {}
